Repository Efimj/Shkiper, pull requests merged in 2024-06, with the labels that each got.

#25 enhancement: LinkPreviewList refactored, updated animations
  app/src/main/java/com/jobik/shkiper/screens/NoteScreen/NoteScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/NoteScreen/NoteScreenContent.kt
  app/src/main/java/com/jobik/shkiper/screens/NoteScreen/NoteViewModel.kt
  app/src/main/java/com/jobik/shkiper/ui/components/fields/HashtagEditor.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/LinkPreviewList.kt
Labels: enhancement

#26 Enhancement/comprehensive reminder dialog refactored
  app/src/main/java/com/jobik/shkiper/screens/NoteListScreen/NoteListScreenContent/NoteListScreenReminderCheck.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/NoteCard.kt
  app/src/main/java/com/jobik/shkiper/ui/components/modals/CreateReminderDialog.kt
Labels: enhancement

#27 Enhancement/update-settings-item-animatins
  app/src/main/java/com/jobik/shkiper/screens/ArchiveNotesScreen/ArchiveNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/BasketNotesScreen/BasketNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/NoteListScreen/NoteListCalendarContent/ScreenCalendarContent.kt
  app/src/main/java/com/jobik/shkiper/screens/NoteListScreen/NoteListScreenContent/NoteListScreenContent.kt
  app/src/main/java/com/jobik/shkiper/screens/NoteScreen/NoteScreenRemindersContent.kt
  app/src/main/java/com/jobik/shkiper/screens/PurchaseScreen/PurchaseScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/SettingsScreen/SettingsScreen.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/SettingsItem.kt
  app/src/main/java/com/jobik/shkiper/ui/components/fields/SearchBar.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/ScreenStub.kt
  app/src/main/java/com/jobik/shkiper/widgets/screens/NoteSelectionScreen/NoteSelectionScreen.kt
Labels: enhancement

#28 enhancement: reminder screen updated
  app/src/main/java/com/jobik/shkiper/ui/components/modals/CreateReminderDialog.kt
Labels: enhancement

#29 gradle code version updated
  gradle/libs.versions.toml
Labels: enhancement

#30 enhancement: reminder dialog resigned
  app/src/main/java/com/jobik/shkiper/ui/components/modals/CreateReminderDialog.kt
Labels: enhancement

#31 enhancement: reminder dialog added on resume lifecycle event to observe notification settings
  app/src/main/java/com/jobik/shkiper/ui/components/modals/CreateReminderDialog.kt
Labels: enhancement

#32 enhancement: NoteListScreenReminderCheck added on resume lifecycle event to observe notification settings
  app/src/main/java/com/jobik/shkiper/screens/NoteListScreen/NoteListScreenContent/NoteListScreenReminderCheck.kt
Labels: enhancement

#33 enhancement: DonateBanner updated
  app/src/main/java/com/jobik/shkiper/screens/NoteListScreen/NoteListScreenContent/NoteListScreenContent.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/DonateBanner.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/DonateBannerProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/BannerList.kt
Labels: enhancement

#34 font sizes updated
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/RichTextBottomToolBar.kt
Labels: enhancement

#36 fixed: opening the reminder menu after closing it and press again
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreenRemindersContent.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteViewModel.kt
  app/src/main/java/com/jobik/shkiper/ui/helpers/SetRichTextDefaultStyles.kt
Labels: bug

#37 fixed: statistics presentation truncates values
  app/src/main/java/com/jobik/shkiper/services/statistics/StatisticsData.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/StatisticsCard.kt
Labels: bug

#38 enhancement: save and load backup dialog updated
  app/src/main/java/com/jobik/shkiper/screens/settings/SettingsScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/settings/SettingsViewModel.kt
  app/src/main/java/com/jobik/shkiper/services/backup/BackupService.kt
Labels: enhancement

#41 Feature/font scaling setting
  app/src/main/java/com/jobik/shkiper/NotepadApplication.kt
  app/src/main/java/com/jobik/shkiper/SharedPreferencesKeys.kt
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/activity/ShareReceiverActivity.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AppIconSelector.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/FontScaleSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomAppBarProvider.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreenRemindersContent.kt
  app/src/main/java/com/jobik/shkiper/ui/components/fields/CustomSlider.kt
  app/src/main/java/com/jobik/shkiper/ui/components/fields/HashtagEditor.kt
  app/src/main/java/com/jobik/shkiper/ui/components/modals/BottomSheetActions.kt
  app/src/main/java/com/jobik/shkiper/util/ContextUtils.kt
  app/src/main/java/com/jobik/shkiper/util/settings/SettingsManager.kt
  app/src/main/java/com/jobik/shkiper/util/settings/SettingsState.kt
  app/src/main/java/com/jobik/shkiper/widgets/config/ConfigWidgetActivity.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#42 Feature/advanced updating settings
  app/build.gradle.kts
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedApplicationSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedUpdatesSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/FontScaleSettings.kt
  app/src/main/java/com/jobik/shkiper/ui/components/buttons/CustomSwitch.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/SettingsItem.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/SettingsGroup.kt
  app/src/main/java/com/jobik/shkiper/util/ContextUtils.kt
  app/src/main/java/com/jobik/shkiper/util/settings/SettingsState.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/splash_theme.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: enhancement

#43 Feature/advanced security settings
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedSecureSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedSettings.kt
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedUpdatesSettings.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/SettingsGroup.kt
  app/src/main/java/com/jobik/shkiper/ui/helpers/SecureModeManager.kt
  app/src/main/java/com/jobik/shkiper/util/settings/SettingsState.kt
  app/src/main/java/com/jobik/shkiper/widgets/components/NoteWidgetContent.kt
  app/src/main/java/com/jobik/shkiper/widgets/config/ConfigWidgetActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#45 Fix/sturtap app note transition
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/navigation/NavigationHelpers.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/AppLayout.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/ScreenWrapper.kt
  app/src/main/java/com/jobik/shkiper/screens/onboarding/OnBoardingScreen.kt
Labels: bug, enhancement

#46 feat: refactored transition when start destination is note screen
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/ScreenWrapper.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteViewModel.kt
  app/src/main/java/com/jobik/shkiper/util/Startup.kt
Labels: bug, enhancement

#47 feat: in app updates
  app/src/main/java/com/jobik/shkiper/screens/advancedSettings/AdvancedUpdatesSettings.kt
  app/src/main/java/com/jobik/shkiper/services/inAppUpdates/InAppUpdatesService.kt
Labels: bug, enhancement

#48 Fix/minor
  app/src/main/java/com/jobik/shkiper/helpers/IntentHelper.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/AppNavigationBar.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomAppBarProvider.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreenHeader.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListCalendarContent/ScreenCalendarContent.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreenContent/NoteListScreenContent.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/DonateBannerProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/components/fields/SearchBar.kt
Labels: enhancement

#50 Enhancement/shered transition
  app/src/main/java/com/jobik/shkiper/navigation/NavigationAnimations.kt
  app/src/main/java/com/jobik/shkiper/navigation/SetupHomePageNavGraph.kt
  app/src/main/java/com/jobik/shkiper/screens/basket/BasketNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/AppLayout.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomAppBarProvider.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomBarViewModel.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/ScreenWrapper.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreenContent.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreenFooter.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteScreenHeader.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteViewModel.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreenContent/NoteListScreenContent.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/NoteCard.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/Counter.kt
  app/src/main/java/com/jobik/shkiper/ui/components/layouts/notesList.kt
  app/src/main/java/com/jobik/shkiper/ui/helpers/LocalProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/modifiers/sharedTransition.kt
  app/src/main/java/com/jobik/shkiper/widgets/screens/noteSelection/NoteSelectionScreen.kt
Labels: enhancement

#52 Enhancement/move calendar screen to route
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/navigation/NavigationAnimations.kt
  app/src/main/java/com/jobik/shkiper/navigation/Route.kt
  app/src/main/java/com/jobik/shkiper/navigation/RouteHelper.kt
  app/src/main/java/com/jobik/shkiper/navigation/SetupHomePageNavGraph.kt
  app/src/main/java/com/jobik/shkiper/screens/archive/ArchiveNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/basket/BasketNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/calendar/CalendarViewModel.kt
  app/src/main/java/com/jobik/shkiper/screens/calendar/FullScreenCalendar.kt
  app/src/main/java/com/jobik/shkiper/screens/calendar/ScreenCalendarContent.kt
  app/src/main/java/com/jobik/shkiper/screens/calendar/ScreenCalendarTopBar.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/AppLayout.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomAppBarProvider.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreenActionBar.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreenContent/NoteListScreenContent.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreenReminderCheck.kt
  app/src/main/java/com/jobik/shkiper/screens/settings/SettingsScreen.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/DonateBannerProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/NoteCard.kt
  app/src/main/java/com/jobik/shkiper/ui/helpers/LocalProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/modifiers/sharedTransition.kt
  app/src/main/java/com/jobik/shkiper/viewmodels/NotesViewModel.kt
Labels: enhancement

#53 Enhancement/type safety navigation
  app/build.gradle.kts
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/navigation/NavigationAnimations.kt
  app/src/main/java/com/jobik/shkiper/navigation/NavigationHelpers.kt
  app/src/main/java/com/jobik/shkiper/navigation/Route.kt
  app/src/main/java/com/jobik/shkiper/navigation/RouteHelper.kt
  app/src/main/java/com/jobik/shkiper/navigation/Screen.kt
  app/src/main/java/com/jobik/shkiper/navigation/SetupHomePageNavGraph.kt
  app/src/main/java/com/jobik/shkiper/screens/archive/ArchiveNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/basket/BasketNotesScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/calendar/CalendarScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/AppLayout.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomAppBarProvider.kt
  app/src/main/java/com/jobik/shkiper/screens/note/NoteViewModel.kt
  app/src/main/java/com/jobik/shkiper/screens/noteListScreen/NoteListScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/settings/SettingsScreen.kt
  app/src/main/java/com/jobik/shkiper/ui/components/cards/DonateBannerProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/components/modals/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/jobik/shkiper/util/Startup.kt
  app/src/main/java/com/jobik/shkiper/viewmodels/NotesViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement

#54 Enhancement/navigation bar animation
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/AppNavigationBar.kt
  app/src/main/java/com/jobik/shkiper/screens/layout/NavigationBar/BottomAppBarProvider.kt
  app/src/main/java/com/jobik/shkiper/ui/helpers/dp.kt
Labels: enhancement

#60 add-tr-language
  app/src/main/res/values-tr/strings.xml
Labels: enhancement

#61 Add Vietnamese strings.xml
  app/src/main/res/values-vi/strings.xml
Labels: enhancement

#62 Enhancement/localization update
  app/src/main/java/com/jobik/shkiper/NotepadApplication.kt
  app/src/main/java/com/jobik/shkiper/activity/MainActivity.kt
  app/src/main/java/com/jobik/shkiper/screens/settings/SettingsScreen.kt
  app/src/main/java/com/jobik/shkiper/screens/settings/SettingsViewModel.kt
  app/src/main/java/com/jobik/shkiper/services/localization/LocaleHelper.kt
  app/src/main/java/com/jobik/shkiper/services/localization/Localization.kt
  app/src/main/java/com/jobik/shkiper/util/ContextUtils.kt
  app/src/main/java/com/jobik/shkiper/util/settings/Localization.kt
  app/src/main/java/com/jobik/shkiper/util/settings/SettingsState.kt
  app/src/main/java/com/jobik/shkiper/widgets/config/ConfigWidgetActivity.kt
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values/non_translatable.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement
